# Generated by Django 3.1 on 2020-08-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0121_auto_20200810_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collectiontranslation',
            name='description_html',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='product',
            name='description_html',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='producttranslation',
            name='description_html',
            field=models.TextField(blank=True),
        ),
    ]
