# Generated by Django 3.1 on 2020-08-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0126_auto_20200826_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='compare_at_price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
