# Generated by Django 3.1 on 2020-08-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0131_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
