# Generated by Django 3.1 on 2020-09-08 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0134_auto_20200829_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='has_variants',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='is_digital',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='is_shipping_required',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='selected_options',
        ),
    ]
