# Generated by Django 3.1 on 2020-09-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0135_auto_20200908_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vendor',
            new_name='product_vendor',
        ),
    ]
