# Generated by Django 3.1 on 2020-09-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0136_auto_20200910_1740'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductVendor',
            new_name='Vendor',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_vendor',
            new_name='vendor',
        ),
    ]
