# Generated by Django 3.1 on 2020-09-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0137_auto_20200910_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
