# Generated by Django 3.1 on 2020-09-14 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0139_auto_20200912_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedvariantattribute',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantassignments', to='product.attribute'),
        ),
    ]
