# Generated by Django 3.1 on 2020-09-14 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0140_auto_20200914_2203'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attributeproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attributeproduct',
            name='assigned_products',
        ),
        migrations.RemoveField(
            model_name='attributeproduct',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='attributeproduct',
            name='product_type',
        ),
        migrations.RenameField(
            model_name='assignedvariantattribute',
            old_name='assignment',
            new_name='attribute',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='product_types',
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='product_variant_types',
        ),
        migrations.AddField(
            model_name='assignedproductattribute',
            name='attribute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productassignments', to='product.attribute'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='assignedproductattribute',
            unique_together={('product', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='assignedvariantattribute',
            unique_together={('variant', 'attribute')},
        ),
        migrations.DeleteModel(
            name='AttributeVariant',
        ),
        migrations.RemoveField(
            model_name='assignedproductattribute',
            name='assignment',
        ),
        migrations.DeleteModel(
            name='AttributeProduct',
        ),
    ]
