# Generated by Django 3.1 on 2020-09-15 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0141_auto_20200914_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedvariantattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantattributes', to='product.attribute'),
        ),
    ]
