# Generated by Django 3.1 on 2020-09-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0142_auto_20200915_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='charge_taxes',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='charge_taxes',
            field=models.BooleanField(default=True),
        ),
    ]
