# Generated by Django 3.1 on 2020-09-17 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0143_auto_20200917_1949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='require_shipping',
            new_name='requires_shipping',
        ),
    ]
