# Generated by Django 3.1 on 2020-10-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0023_auto_20201003_2131'),
        ('product', '0145_auto_20200924_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='shipping_profile',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='shipping.shippingprofile'),
            preserve_default=False,
        ),
    ]
