# Generated by Django 3.1 on 2020-10-09 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0026_auto_20201009_1215'),
        ('product', '0146_productvariant_shipping_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='shipping_profile',
            field=models.ForeignKey(on_delete=models.SET(1), related_name='product_variants', to='shipping.shippingprofile'),
        ),
    ]
