# Generated by Django 3.1 on 2020-10-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0039_auto_20201019_2237'),
        ('product', '0147_auto_20201009_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='shipping_profile',
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_profile',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), related_name='products', to='shipping.shippingprofile'),
            preserve_default=False,
        ),
    ]
