# Generated by Django 3.1 on 2020-10-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0148_auto_20201021_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_base_variant',
            field=models.BooleanField(default=False),
        ),
    ]
