# Generated by Django 3.1 on 2020-10-25 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0149_productvariant_is_base_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='is_base_variant',
        ),
        migrations.AddField(
            model_name='product',
            name='base_variant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.productvariant'),
        ),
    ]
