# Generated by Django 3.1 on 2020-10-15 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('code', models.CharField(max_length=2)),
                ('continent', models.CharField(max_length=128)),
                ('phone_number_prefix', models.IntegerField(editable=False, null=True)),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ('-display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CountryZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('code', models.CharField(max_length=2)),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='country.country')),
            ],
            options={
                'ordering': ('-display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='CountryZoneTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('country_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='country.countryzone')),
            ],
            options={
                'ordering': ('language_code', 'country_zone', 'pk'),
                'unique_together': {('language_code', 'country_zone')},
            },
        ),
        migrations.CreateModel(
            name='CountryTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='country.country')),
            ],
            options={
                'ordering': ('language_code', 'country', 'pk'),
                'unique_together': {('language_code', 'country')},
            },
        ),
    ]
