# Generated by Django 3.1 on 2020-10-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryzone',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
