# Generated by Django 3.1 on 2020-10-19 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20201017_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('code', models.CharField(max_length=10)),
                ('display_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ('-display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProvinceTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='country.province')),
            ],
            options={
                'ordering': ('language_code', 'province', 'pk'),
                'unique_together': {('language_code', 'province')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='countryzonetranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='countryzonetranslation',
            name='country_zone',
        ),
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='CountryZone',
        ),
        migrations.DeleteModel(
            name='CountryZoneTranslation',
        ),
        migrations.AddField(
            model_name='province',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='country.country'),
        ),
    ]
