# Generated by Django 3.1 on 2020-10-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_auto_20201019_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='country',
            name='phone_number_prefix',
        ),
        migrations.AlterField(
            model_name='province',
            name='code',
            field=models.CharField(max_length=6),
        ),
    ]
