# Generated by Django 3.1 on 2020-10-03 14:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0019_remove_shippingmethod_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None)),
                ('shipping_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.shippingzone')),
            ],
            options={
                'permissions': (('manage_shipping', 'Manage shipping.'),),
            },
        ),
    ]
