# Generated by Django 3.1 on 2020-10-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0020_shippingcountry'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'permissions': (('manage_shipping', 'Manage shipping.'),),
            },
        ),
        migrations.RemoveField(
            model_name='shippingzone',
            name='default',
        ),
        migrations.DeleteModel(
            name='ShippingCountry',
        ),
    ]
