# Generated by Django 3.1 on 2020-10-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0022_shippingzone_shipping_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingprofile',
            name='default',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
