# Generated by Django 3.1 on 2020-10-05 15:43

from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models
import measurement.measures.mass
import saleor.core.weight


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0023_auto_20201003_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingmethod',
            name='maximum_order_price_amount',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='maximum_order_weight',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='minimum_order_price_amount',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='minimum_order_weight',
        ),
        migrations.RemoveField(
            model_name='shippingmethod',
            name='type',
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='shipping_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_zones', to='shipping.shippingprofile'),
        ),
        migrations.CreateModel(
            name='ShippingMethodCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('price', 'Price based shipping'), ('weight', 'Weight based shipping')], max_length=30)),
                ('minimum_order_price_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('maximum_order_price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('minimum_order_weight', django_measurement.models.MeasurementField(blank=True, default=saleor.core.weight.zero_weight, measurement=measurement.measures.mass.Mass, null=True)),
                ('maximum_order_weight', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True)),
                ('shipping_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_method_conditions', to='shipping.shippingmethod')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
