# Generated by Django 3.1 on 2020-10-05 15:56

from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models
import measurement.measures.mass
import saleor.core.weight


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0024_auto_20201005_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='maximum_order_price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='maximum_order_weight',
            field=django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='minimum_order_price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='minimum_order_weight',
            field=django_measurement.models.MeasurementField(blank=True, default=saleor.core.weight.zero_weight, measurement=measurement.measures.mass.Mass, null=True),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='type',
            field=models.CharField(choices=[('price', 'Price based shipping'), ('weight', 'Weight based shipping')], default='PRICE_BASED', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shippingzone',
            name='shipping_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipping.shippingprofile'),
        ),
        migrations.DeleteModel(
            name='ShippingMethodCondition',
        ),
    ]
