# Generated by Django 3.1 on 2020-10-10 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0026_auto_20201009_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingzone',
            name='shipping_profile',
        ),
        migrations.CreateModel(
            name='ShippingProfileWarehouseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shippnig_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_profile_warehouse_groups', to='shipping.shippingprofile')),
            ],
            options={
                'permissions': (('manage_shipping', 'Manage shipping.'),),
            },
        ),
    ]
