# Generated by Django 3.1 on 2020-10-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0027_auto_20201010_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingzone',
            name='shipping_profile_warehouse_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_zones', to='shipping.shippingprofilewarehousegroup'),
            preserve_default=False,
        ),
    ]
