# Generated by Django 3.1 on 2020-10-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0028_shippingzone_shipping_profile_warehouse_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingmethod',
            name='type',
            field=models.CharField(choices=[('price', 'Price based shipping'), ('weight', 'Weight based shipping'), ('GENERAL', 'General shipping')], max_length=30),
        ),
    ]
