# Generated by Django 3.1 on 2020-10-15 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0030_auto_20201015_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingcountry',
            old_name='country',
            new_name='code',
        ),
    ]
