# Generated by Django 3.1 on 2020-10-17 14:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0031_auto_20201015_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcountry',
            name='zones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=None),
        ),
    ]
