# Generated by Django 3.1 on 2020-10-17 15:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0034_auto_20201017_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingcountry',
            name='zones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=[], size=None),
        ),
    ]
