# Generated by Django 3.1 on 2020-10-17 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0036_auto_20201017_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingprofilewarehousegroup',
            name='shippnig_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_groups', to='shipping.shippingprofile'),
        ),
    ]
