# Generated by Django 3.1 on 2020-10-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0037_auto_20201017_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingprofilewarehousegroup',
            old_name='shippnig_profile',
            new_name='shipping_profile',
        ),
    ]
