# Generated by Django 3.1 on 2020-10-19 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0038_auto_20201018_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingcountry',
            old_name='zones',
            new_name='provinces',
        ),
    ]
