# Generated by Django 3.1 on 2020-10-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0039_auto_20201019_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingprofile',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
