# Generated by Django 3.1 on 2020-10-29 19:55

from django.db import migrations, models
import django.db.models.deletion
import django_measurement.models
import measurement.measures.mass
import saleor.core.weight


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0040_auto_20201029_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethodDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('price', 'Price based delivery'), ('weight', 'Weight based delivery'), ('GENERAL', 'General delivery')], max_length=30)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('minimum_order_price_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('maximum_order_price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('minimum_order_weight', django_measurement.models.MeasurementField(blank=True, default=saleor.core.weight.zero_weight, measurement=measurement.measures.mass.Mass, null=True)),
                ('maximum_order_weight', django_measurement.models.MeasurementField(blank=True, measurement=measurement.measures.mass.Mass, null=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ShippingZoneMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_method_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shipping.deliverymethoddefinition')),
                ('shipping_zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shipping.shippingzone')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryMethodDefinitionTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_method_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='shipping.deliverymethoddefinition')),
            ],
            options={
                'unique_together': {('language_code', 'delivery_method_definition')},
            },
        ),
    ]
