# Generated by Django 3.1 on 2020-10-29 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0041_deliverymethoddefinition_deliverymethoddefinitiontranslation_shippingzonemethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingzonemethod',
            name='shipping_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_zone_methods', to='shipping.shippingzone'),
        ),
    ]
