# Generated by Django 3.1 on 2020-10-29 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0042_auto_20201029_1959'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='deliverymethoddefinitiontranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='deliverymethoddefinitiontranslation',
            name='delivery_method_definition',
        ),
        migrations.RemoveField(
            model_name='shippingzonemethod',
            name='delivery_method_definition',
        ),
        migrations.RemoveField(
            model_name='shippingzonemethod',
            name='shipping_zone',
        ),
        migrations.DeleteModel(
            name='DeliveryMethodDefinition',
        ),
        migrations.DeleteModel(
            name='DeliveryMethodDefinitionTranslation',
        ),
        migrations.DeleteModel(
            name='ShippingZoneMethod',
        ),
    ]
