# Generated by Django 3.1 on 2020-10-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('site', '0025_auto_20191024_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='company_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address'),
        ),
    ]
