# Generated by Django 3.1 on 2020-08-21 19:44

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagedtarget',
            name='content_file',
            field=versatileimagefield.fields.VersatileImageField(null=True, upload_to='staged_files'),
        ),
    ]
