# Generated by Django 3.1 on 2020-08-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20200821_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagedtarget',
            name='content_file',
            field=models.FileField(null=True, upload_to='staged_files'),
        ),
    ]
