# Generated by Django 3.1 on 2020-10-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('warehouse', '0011_auto_20200714_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.address'),
        ),
    ]
