# Generated by Django 3.1 on 2020-10-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0027_auto_20201010_1142'),
        ('warehouse', '0012_auto_20201005_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='shipping_zones',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='shipping_profile_warehouse_groups',
            field=models.ManyToManyField(blank=True, related_name='warehouses', to='shipping.ShippingProfileWarehouseGroup'),
        ),
    ]
