# Generated by Django 3.1 on 2020-10-05 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('checkout', '0027_auto_20200810_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='billing_address',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='address.address'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='shipping_address',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='address.address'),
        ),
    ]
