# Generated by Django 3.1 on 2020-09-26 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0145_auto_20200924_2343'),
        ('menu', '0018_auto_20200709_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category',
        ),
        migrations.AddField(
            model_name='menu',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
    ]
