# Generated by Django 3.1 on 2020-10-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('account', '0047_auto_20200810_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='users', to='address.Address'),
        ),
    ]
