# Generated by Django 3.1 on 2020-10-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0048_auto_20201009_1127'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
