# Generated by Django 3.1 on 2020-10-23 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themefile',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='ThemeAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('content_file', models.FileField(null=True, upload_to='theme_assets')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='theme.theme')),
            ],
            options={
                'ordering': ('pk',),
                'unique_together': {('path', 'theme')},
            },
        ),
    ]
