# Generated by Django 3.1 on 2020-10-29 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_auto_20201023_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeLocale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ThemeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AddField(
            model_name='theme',
            name='settings_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='theme',
            name='settings_schema',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='ThemeFile',
        ),
        migrations.AddField(
            model_name='themetemplate',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='theme.theme'),
        ),
        migrations.AddField(
            model_name='themelocale',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='theme.theme'),
        ),
        migrations.AlterUniqueTogether(
            name='themetemplate',
            unique_together={('path', 'theme')},
        ),
        migrations.AlterUniqueTogether(
            name='themelocale',
            unique_together={('language_code', 'theme')},
        ),
    ]
