# Generated by Django 3.1 on 2020-10-29 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20201029_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='author',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='documentation_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='support_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='themelocale',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='theme',
            name='version',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
