# Generated by Django 3.1 on 2020-11-05 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_auto_20201029_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=256)),
                ('content_file', models.FileField(null=True, upload_to='theme_files')),
                ('raw_content', models.TextField(null=True)),
                ('content_type', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='theme.theme')),
            ],
            options={
                'ordering': ('pk',),
                'unique_together': {('path', 'theme')},
            },
        ),
    ]
